### ISSUE TITLE
Missing space from generated latex

### ISSUE THREAD

**Issue by samgabriel** [asnunes/mathml-to-latex#13]
When passing this mathmml:
`<math xmlns=\"http://www.w3.org/1998/Math/MathML\">
    <mi>A</mi>
    <mo>=</mo>
    <mi>π</mi>
    <msup>
      <mrow>
        <mi>r</mi>
      </mrow>
      <mrow>
        <mn>2</mn>
      </mrow>
    </msup>
  </math>`
Result should be A=\pi r^{2} but the result become A=\pir^{2} missing space after \pi

**Comment by only-yao** [comment]
> When passing this mathmml: `<math xmlns=\"http://www.w3.org/1998/Math/MathML\"> <mi>A</mi> <mo>=</mo> <mi>π</mi> <msup> <mrow> <mi>r</mi> </mrow> <mrow> <mn>2</mn> </mrow> </msup> </math>` Result should be A=\pi r^{2} but the result become A=\pir^{2} missing space after \pi

I encountered the same issue. Have you resolved it?

**Comment by asnunes** [comment]
Fixed on #17 
Thanks for the report
