### ISSUE TITLE
Attribute 'mathvariant="double-struck"' has no effect

### ISSUE THREAD

**Issue by RyanHanekamp** [asnunes/mathml-to-latex#14]
mathml-to-latex version 1.2.0
`
<math><msup><mrow><mi mathvariant="double-struck">R</mi></mrow><mrow><mi>n</mi></mrow></msup></math>
`

This is converted to 'R^{n}'

It should be converted to '\mathbb{R}^{n}' or something similar.

https://developer.mozilla.org/en-US/docs/Web/MathML/Global_attributes/mathvariant

Thanks,

-Ryan

**Comment by asnunes** [comment]
Implemented in #17 
Thanks for the report
