### ISSUE TITLE
Issue in Safari browser 

### ISSUE THREAD

**Issue by Suhovft49** [asnunes/mathml-to-latex#4]
```
ErrorHandler.prototype._mathGenericMissingValue = function () {
        return /(?<=\<.*)(\w+=(?!(\"|\')))/gm;
};
```

Result: Invalid regular expression: invalid group specifier name

It happens because Safari doesn't support lookbehind yet

**Comment by asnunes** [comment]
Hi, @Suhovft49! Thank you for your report! I can't see another way to offer support to non lookbehind browsers right now. This feature handle invalid tags like 

````
<root>
  <math>
  <mfenced open='{' close= >
    <mn>3</mn>
  </mfenced>
  </math>
</root>
````

where open attributes like `close=` could cause parse errors and so are replaced by an empty string. This use case is covered by our tests. If you want to fix that, fell free to open a PR.

**Comment by asnunes** [comment]
Reopening due to #9

**Comment by asnunes** [comment]
#9 from @caleb-flores has been merged fixing the problem
