### ISSUE TITLE
How to user in angular 11 application

### ISSUE THREAD

**Issue by Asifislam110** [asnunes/mathml-to-latex#7]
Can you please provide some sample code.

**Comment by asnunes** [comment]
Hi @Asifislam110. I don't have an Angular 11 background to give you an example, but I belive it should be a straight foward implementation. You should just replace `require` by `import` syntax. Are you facing any problem or error when implementing that on angular. Can you share it?

**Comment by zbh876325764** [comment]
Why will the extra parentheses be parsed when there are subscripts

example：
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
    <msub>
        <mi>𝑎</mi>
        <mn>0</mn>
    </msub>
</math>

result：'\left(𝑎\right)_{0}'

but i want '𝑎_{0}'
