### ISSUE TITLE
Why will the extra parentheses be parsed when there are subscripts

### ISSUE THREAD

**Issue by zbh876325764** [asnunes/mathml-to-latex#8]
example：
`<math display="block" xmlns="http://www.w3.org/1998/Math/MathML"> <msub> <mi>𝑎</mi> <mn>0</mn> </msub> </math>`

result：'\left(𝑎\right)_{0}'

but i want '𝑎_{0}'

**Comment by asnunes** [comment]
Hello, @zbh876325764. Sorry for taking too long to respond. I missed this issue. This is just the way the library is implemented. It does not distingue between one or many characters, so for one char in LaTeX, parentheses are optional, but they must be applied for many chars cases, so they are always applied to accomplish the most restrive case.
